# Site settings
title: MathJax
email: info@mathjax.org
description: "Beautiful math in all browsers."
baseurl: ""
url: "https://www.mathjax.org"
author: MathJax Consortium
TimeZone: America/New_York

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
sass:
    sass_dir: css

# GitHub
repository: mathjax/mathjax

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
